### ISSUE TITLE
problem with resp.Body.close()

### ISSUE THREAD

**Issue by legret-lin** [Albert-Zhan/httpc#1]
I found some people say that if resp is nil, defer resp.Body.close() may cause some problem.
They said that right way to def resp.Body.close() must be like below.
resp, err := http.Get(url)
if nil != resp {
    defer resp.Body.Close()
}
 
if err != nil {
    return err
}

I don't know is that is true.But in my project, I found many close_wait tcp connetcion.I'm not sure what cause that.

**Comment by Albert-Zhan** [comment]
目前最新版本已经临时解决了请求过多resp.Body.Close()未关闭，导致未关闭的tcp链接过多的问题，但是并不是完美的解决方案，后面会对该项目进行重构，具体请查看readme文件
