### ISSUE TITLE
简单的demo都会panic

### ISSUE THREAD

**Issue by crossci** [Albert-Zhan/httpc#2]
send接口内部的this.data是nil
this.request,err=http.NewRequest(this.method,this.url,this.data.Encode())

**Comment by Albert-Zhan** [comment]
目前请使用release的1.0.1版本，2.0.0处于开发中，此问题目前已经解决了，涉及到其他模块暂未提交

**Comment by crossci** [comment]
好的 多谢回复

**Comment by crossci** [comment]
requie github.com/Albert-Zhan/httpc v1.0.1

会显示 unknown revision v1.0.1

**Comment by crossci** [comment]
在go mod 里面我需要怎么写

**Comment by hpf0532** [comment]
> 在go mod 里面我需要怎么写

go get github.com/Albert-Zhan/httpc@1.0.1
